### ISSUE TITLE
Erro !validateForm() e sincronia wordpress.org com Github 

### ISSUE THREAD

**Issue by brasofilo** [v-verner/woo-getnet#1]
Oi Vinicius, 
tá dando um erro 404 pro `/app/assets/main.prod.js` e vi ele está presente aqui no Github mas [tá faltando no WP.org](https://plugins.trac.wordpress.org/browser/vverner-getnet-gateway/#trunk/app/assets).

Rodando a versão do Github dá erro de "Por favor, confira os dados do seu cartão", vi no código que é um erro na function `validateForm` mas não entendo o porquê... inclusive rodando essa mesma função no console ela funciona beleza (afinal os inputs estão todos preenchidos).

Estou rodando em modo Sandbox.  
Obrigado!

**Comment by brasofilo** [comment]
Na verdade o erro é no arquivo `main.prod.js`:

```
        if (
            (o
                .find("#place_order")
                .attr("disabled", !0)
                .text("Validando Cartão..."),
            i.each(function () {
                if (!r(this).val()) return !1;
            }),
            !(function (e) {
                var t = e.split("/"),
                    a = new Date(t[0] + "-01-20" + t[1]);
                return (
                    "Invalid Date" != a &&
                    !(new Date().getFullYear() > a.getFullYear())
                );
            })(r("#getnet_expdate").val()))
        )
            return alert("Por favor, confira os dados do seu cartão"), !1;
```

Eu desliguei todos os plugins (menos WC, BR Market e VVerner), removi o mu-plugins, e passei o theme pra TwentyTwenty e o erro continua acontecendo..
Removendo o bloco de código acima o pagamento é aceito e processado

**Comment by v-verner** [comment]
Opa, boa tarde @brasofilo 

Vish, pelo jeito deu erro ao compilar a versão de produção, irei corrigir aqui.

Sobre a falta de arquivos, vou ver o que pode ter acontecido.

Acredito que na segunda-feira eu consiga parar para fazer essas edições. Obrigado pelo aviso!

**Comment by v-verner** [comment]
@brasofilo , ajustado

**Comment by brasofilo** [comment]
Oi Vinicius,
o erro de ValidateForm continua acontecendo usando o Sandbox. Isso acontece com o tema default e sem nenhum plugin ativo exceto Woo, VV e WooBR
![image](https://user-images.githubusercontent.com/1542052/104219940-88276500-541d-11eb-8799-e93606ad6c2b.png)
