### ISSUE TITLE
Erro de validação de data de validade do cartão de crédito 

### ISSUE THREAD

**Issue by dairan** [v-verner/woo-getnet#2]
No checkout, após preencher todos os dados e apertar no botão Finalizar Compra, aparece a seguinte mensagem de erro, não importa que data eu coloque: 

`Por favor, confirma a data de vencimento do seu cartão`

veja imagem:
![Screen Shot 2021-06-18 at 00 30 32](https://user-images.githubusercontent.com/352361/122502208-91b88880-cfcc-11eb-97a9-3df78b431f2b.png)

Modifiquei o arquivo [checkout.min.js](https://github.com/v-verner/woo-getnet/blob/9a627c9bf8ffdf7f8477a72beacfcb7d1ff450a0/app/assets/public/checkout.min.js), no trecho onde tem o código abaixo e funcionou. 

`o = new Date(t[0] , "-01-20" , t[1]`

Seria algum tipo de bug ou algum problema em meu setup?!!

Grato.

**Comment by v-verner** [comment]
Opa, bah estranho isso, vou fazer um teste com essas datas informadas e volto a retornar aqui

Data para teste: 12/25

**Comment by v-verner** [comment]
@dairan não consegui replicar teu erro aqui, pode me passar a URL do teu ambiente para eu testar?

**Comment by dairan** [comment]
> @dairan não consegui replicar teu erro aqui, pode me passar a URL do teu ambiente para eu testar?

Infelizmente eu tive que sair do projeto... 
Acho melhor então fechar o caso

Obrigado pela atenção!
