### ISSUE TITLE
Opção de pagamento no Boleto e PIX

### ISSUE THREAD

**Issue by caiofellipe** [v-verner/woo-getnet#4]
Olá, vocês tem a pretensão de criarem as opções de pagamento no boleto ou pix ?

**Comment by v-verner** [comment]
Oi @caiofellipe , na semana passada criamos a nova versão com o pagamento de boleto, porém sem a confirmação de pagamento automática (esse será nosso próximo passo no roadmap).

Sobre PIX, será implementado apenas após a finalização dos boletos
